apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    {{- include "charts.labels" . | nindent 4 }}
  name: {{ include "charts.fullname" . }}
  annotations:
    haproxy.router.openshift.io/timeout: {{ .Values.route.timeout }}
spec:
  host: {{ include "charts.fullname" . }}.{{ .Values.domain }}
  port:
    targetPort: {{ .Values.route.targetPort }}
  to:
    kind: Service
    name: {{ include "charts.fullname" . }}
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect